//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeReport
    {
        public int WeekNr { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Project_ID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Project Project { get; set; }
    }
}
